map_data = [
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                               X",
"X XXX XXX XXXXXX XXXXXX XXX XXX X",
"X X X X X X    X X    X X X X X X",
"X XXX X X XXXXXX XXXXXX X X XXX X",
"X     XXX X    X X    X XXX     X",
"XXXXX       XX X X XX       XXXXX",
"X     XXXXX           XXXXX     X",
"X XXX       XXXXXXXXX       XXX X",
"X     XXXXX           XXXXX     X",
"X XXX       XXXX XXXX       XXX X",
"X X X XXXXX X  X X  X XXXXX X X X",
"X X X X   X X  X X  X X   X X X X",
"X X X X   X X  X X  X X   X X X X",
"X X X XXXXX X  X X  X XXXXX X X X",
"X XXX       XXXX XXXX       XXX X",
"X     XXXXX           XXXXX     X",
"X XXX       XXXXXXXXX       XXX X",
"X     XXXXX           XXXXX     X",
"XXXXX       XX X X XX       XXXXX",
"X     XXX X    X X    X XXX     X",
"X XXX X X XXXXXX XXXXXX X X XXX X",
"X X X X X X    X X    X X X X X X",
"X XXX XXX XXXXXX XXXXXX XXX XXX X",
"X                               X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
]